import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "brand-primary": "var(--color-brand-primary)",
        "brand-primary-soft": "var(--color-brand-primary-soft)",
        "brand-primary-fg": "var(--color-brand-primary-foreground)",
        "bg-shell": "var(--color-bg-shell)",
        "bg-main": "var(--color-bg-main)",
        "bg-surface": "var(--color-bg-surface)",
        "bg-muted": "var(--color-bg-muted)",
        "bg-subtle": "var(--color-bg-subtle)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-tertiary": "var(--color-text-tertiary)",
        "border-default": "var(--color-border-default)",
        "border-strong": "var(--color-border-strong)",
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        border: "var(--color-border)",
        muted: "var(--color-muted)",
        "muted-fg": "var(--color-muted-foreground)",
        card: "var(--color-card)",
        primary: "var(--color-primary)",
        "primary-fg": "var(--color-primary-foreground)",
        sidebar: "var(--color-sidebar)",
        "sidebar-accent": "var(--color-sidebar-accent)",
        "sidebar-fg": "var(--color-sidebar-foreground)",
        "sidebar-emphasis": "var(--color-sidebar-emphasis)",
        "sidebar-active": "var(--color-sidebar-active)",
        "sidebar-active-border": "var(--color-sidebar-active-border)",
        tile: "var(--color-tile)",
        success: "var(--color-success)",
        "success-fg": "var(--color-success-foreground)",
        error: "var(--color-error)",
        "error-fg": "var(--color-error-foreground)",
        "error-border": "var(--color-error-border)",
        warning: "var(--color-warning)",
        "warning-fg": "var(--color-warning-foreground)",
        accent: "var(--color-accent)",
        "accent-fg": "var(--color-accent-foreground)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-family-mono)"],
        serif: ["var(--font-family-serif)"],
      },
      fontSize: {
        display: ["var(--text-display)", { lineHeight: "var(--leading-display)" }],
        title: ["var(--text-title)", { lineHeight: "var(--leading-title)" }],
        hero: ["var(--text-hero)", { lineHeight: "var(--leading-hero)" }],
        body: ["var(--text-body)", { lineHeight: "var(--leading-body)" }],
        md: ["var(--text-md)", { lineHeight: "var(--leading-md)" }],
        lg: ["var(--text-lg)", { lineHeight: "var(--leading-lg)" }],
        xl: ["var(--text-xl)", { lineHeight: "var(--leading-xl)" }],
        small: ["var(--text-small)", { lineHeight: "var(--leading-small)" }],
        caption: ["var(--text-caption)", { lineHeight: "var(--leading-caption)" }],
        overline: ["var(--text-overline)", { lineHeight: "var(--leading-overline)" }],
        badge: ["var(--text-badge)", { lineHeight: "var(--leading-badge)" }],
        micro: ["var(--text-micro)", { lineHeight: "var(--leading-micro)" }],
      },
      spacing: {
        "space-2xs": "var(--space-2xs)",
        "space-xs": "var(--space-xs)",
        "space-sm": "var(--space-sm)",
        "space-md": "var(--space-md)",
        "space-lg": "var(--space-lg)",
        "space-xl": "var(--space-xl)",
      },
      borderRadius: {
        ui: "var(--radius-ui)",
        "control-sm": "var(--radius-control-sm)",
        "control-md": "var(--radius-control-md)",
        "control-lg": "var(--radius-control-lg)",
        surface: "var(--radius-surface)",
        panel: "var(--radius-panel)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        surface: "var(--shadow-surface)",
        overlay: "var(--shadow-overlay)",
      },
    },
  },
  plugins: [],
};

export default config;
